### ISSUE TITLE
Would it be possible to change this to use volca sync?

### ISSUE THREAD

**Issue by bnolan** [ambinaut/MIDI-to-Digitech-JamMan-Tap-Tempo#1]
It'd be great to get the sync signal from a korg volca and use that, would that be a hard change?

**Comment by ambinaut** [comment]
Do you want use the volca sync signal to create a MIDI clock signal?

**Comment by bnolan** [comment]
I want to recieve volca sync signal and send it to the jamman so that I play guitar loops into the jamman and it stays in clock sync with my volcas doing drums / synth bits :)

**Comment by bnolan** [comment]
Great project btw, thanks.

**Comment by ambinaut** [comment]
Unfortunately that setup is not possible with the JamMan.
best regards

**Comment by bnolan** [comment]
I'll see if I can modify the sketch to receive volca sync, I'll update this issue if I manage it. :)
